services:
  postgres:
    image: postgres:16
    container_name: itq-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: soft
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - itq_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d soft"]
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  itq_pg_data: